version: '3'
services:
  config:
    image: registry.redhat.io/quay/quay-rhel8:v3.6.1
    container_name: config
    restart: always
    privileged: true
    networks:
      - quay
    ports:
      - 80:8080
    environment:
      - DEBUGLOG=false
    command:
      ["config", "redhat"]
    depends_on:
      - pgsql
      - redis
  pgsql:
    image: registry.redhat.io/rhel8/postgresql-10:1
    container_name: pgsql
    restart: always
    privileged: true
    volumes:
      - /var/lib/pgsql/data:/var/lib/pgsql/data:Z
      - ./post-pgsql.sh:/usr/local/bin/post-pgsql.sh
    networks:
      - quay
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USER=quayuser
      - POSTGRESQL_PASSWORD=quaypass
      - POSTGRESQL_DATABASE=quaydb
  redis:
    image: registry.redhat.io/rhel8/redis-5:1
    container_name: redis
    restart: always
    privileged: true
    volumes:
      - /var/lib/redis:/var/lib/redis/data:Z
    networks:
      - quay
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=test123
    depends_on:
      - pgsql
networks:
  quay:
    external: false
